title: OHANA-ROBOT
year: 2025
location: Teshikaga / Kushiro
tags: [robotics, vernacular]
summary: |
  農と暮らしの文脈から立ち上がる、ヴァナキュラー指向のロボット試作群。
images:
  - images/cover.jpg
  - images/detail-1.jpg
  - images/detail-2.jpg

