title: ヴァナキュラーな稲作ロボット
year: 2025
location: Hokkaido / Koinzemi
tags: [robotics, agriculture]
summary: |
  地場の素材・技術・環境に合わせて組み上げる稲作支援ロボットの研究。
images:
  - images/cover.jpg
  - images/field-1.jpg
  - images/field-2.jpg

